//
// SSpec
// Describe.swift
//
// Created by Dimitri Kurashvili on 2017-10-29
//
// Copyright (c) 2017 Dimitri Kurashvili. All rights reserved
//

/// Node which is generated by describe and context functions.
class Describe: Node {
  override init(title: String, parent: Node? = nil, runnable: SSRunnable? = nil) {
    super.init(title: title, parent: parent, runnable: runnable)

    if let parent = self.parent {
      parent.children.append(self)
    }
  }

  override func runInitial() {
    guard let run = runnable else { return }
    run()
  }

  override func runExamples() {
    // TODO: report skip when no runnable
    guard let run = runnable else { return }

    SSpec.currentSession.collectContextStarted(node: self)

    for child in children {
      Node.currentId = child.id
      run()
      child.runExamples()
    }

    SSpec.currentSession.collectContextEnded(node: self)
  }
}
